# Generated by Django 4.2.21 on 2025-05-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='openai_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='assistant',
            name='thread_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
