# Generated by Django 4.2.21 on 2025-05-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0006_assistant_vector_store_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='model',
            field=models.CharField(choices=[('gpt-4', 'gpt-4'), ('gpt-4o', 'gpt-4o'), ('o1-mini', 'o1-mini'), ('o3-mini', 'o3-mini'), ('o:mini', 'o:mini')], default='gpt-4o', max_length=40),
        ),
    ]
